### ISSUE TITLE
ERROR: could not find project file in package at https://github.com/computational-imaging/ThreeDeconv.jl.git

### ISSUE THREAD

**Issue by ZhenhongDu** [computational-imaging/ThreeDeconv.jl#3]
When I hit the key ] in the Julia REPL to ender the Pkg REPL-mode, and run
`pkg> add https://github.com/computational-imaging/ThreeDeconv.jl.git`
There is an error:
`ERROR: could not find project file in package at https://github.com/computational-imaging/ThreeDeconv.jl.git`
I am not familiar with Julia language, does this affect  use？

**Comment by hayatoikoma** [comment]
That's because you were using the latest version of Julia rather than the supported Julia version.
I just supported v1.5. It should work now.

**Comment by ZhenhongDu** [comment]
I sincerely thank you for your response！ @hayatoikoma 
but I still get errors when I install CuArrays：

> ERROR: Unsatisfiable requirements detected for package CuArrays [3a865a2d]:
>  CuArrays [3a865a2d] log:
>  ├─possible versions are: [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0-1.4.7, 1.5.0, 1.6.0, 1.7.0-1.7.3, 2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.2] or uninstalled
>  ├─restricted to versions * by an explicit requirement, leaving only versions [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0-1.4.7, 1.5.0, 1.6.0, 1.7.0-1.7.3, 2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.2]
>  ├─restricted by compatibility requirements with Adapt [79e6a3ab] to versions: [0.2.1, 0.3.0] or uninstalled, leaving only versions: [0.2.1, 0.3.0]
>  │ └─Adapt [79e6a3ab] log:
>  │   ├─possible versions are: [0.3.0-0.3.1, 0.4.0-0.4.2, 1.0.0-1.0.1, 1.1.0, 2.0.0-2.0.2] or uninstalled
>  │   └─restricted by compatibility requirements with CUDA [052768ef] to versions: 2.0.0-2.0.2
>  │     └─CUDA [052768ef] log:
>  │       ├─possible versions are: [0.1.0, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1] or uninstalled
>  │       └─restricted to versions 1.2.0-1 by ThreeDeconv [8923caa7], leaving only versions 1.2.0-1.2.1
>  │         └─ThreeDeconv [8923caa7] log:
>  │           ├─possible versions are: 1.3.0 or uninstalled
>  │           └─ThreeDeconv [8923caa7] is fixed to version 1.3.0
>  └─restricted by compatibility requirements with NNlib [872c559c] to versions: [1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0-1.4.7, 1.5.0, 1.6.0, 1.7.0-1.7.3, 2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.2] or uninstalled — no versions left
>    └─NNlib [872c559c] log:
>      ├─possible versions are: [0.3.2, 0.4.0-0.4.3, 0.5.0, 0.6.0-0.6.6, 0.7.0-0.7.4] or uninstalled
>      └─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.6.5-0.6.6, 0.7.0-0.7.4]
>        └─CUDA [052768ef] log: see above

I have installed cuda10.2 on my computer, but I really don't  know how to fix the problem, do you have any suggestions?

**Comment by hayatoikoma** [comment]
I guess you have installed an older version of CuArrays previously. If you don't know much about Julia, I recommend you to delete the julia directory ($HOME/.julia) and fresh install everything.

**Comment by ZhenhongDu** [comment]
Thank you for your reply, I will try it
